language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

notifications:
  email: false

